name: Bug report
description: Reporte um problema para ajudarmos a resolver.
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Preencha os campos abaixo.
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: O que aconteceu?
      placeholder: Descreva o problema
    validations:
      required: true
  - type: textarea
    id: passos
    attributes:
      label: Passos para reproduzir
      description: Como reproduzir o problema?
      placeholder: 1. ...
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamento esperado
      placeholder: O que deveria acontecer?
    validations:
      required: true
  - type: input
    id: versao
    attributes:
      label: Versão
      placeholder: 'ex: 2.0.0'
    validations:
      required: false
